import Head from "next/head";

import PageShell from "./components/pageShell";

import Hero from "./components/hero";

export default function Home() {
  return (
    <>
      <Head>
        <title>VoyagePath</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageShell pt={0}>
        <Hero />
      </PageShell>
    </>
  );
}
